spring.application.name=Auth-servce

server.port=8081

spring.security.user.name=dev
spring.security.user.password=build

spring.datasource.url=jdbc:postgresql://localhost:5432/authservice
spring.datasource.username=postgres
spring.datasource.password=build@dev

jwt.secret=R8x0s4ZV2YJb9Qk3u7K6e1mTgPpWcA5HnFqLr9XjC0D=
jwt.expiration-ms=900000

wallet.service.base.url=http://localhost:8082